version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/src
      - ./alembic.ini:/alembic.ini
      - ./migrations:/migrations
      - ./.env:/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /src

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - default
 
  celery:
    build: .
    command: celery -A celery_worker worker --loglevel=info
    volumes:
      - ./src:/src
    env_file:
      - .env
    depends_on:
      - redis
      - web
    working_dir: /src
    networks:
      - default

  celery-beat:
    build: .
    command: celery -A celery_worker beat --loglevel=info
    volumes:
      - ./src:/src
    env_file:
      - .env
    depends_on:
      - redis
      - web
    working_dir: /src
    networks:
      - default

volumes:
  postgres_data:
